function cfg = phase3_config(project_root)
%PHASE3_CONFIG Configuration for Phase 3 autopilot and flight-control work.
%
% IMPORTANT
% ---------
% This file intentionally separates:
%   1) values recovered from the earlier project history,
%   2) values that must come from the actual Phase 1/2 MATLAB model,
%   3) initial controller-tuning choices.
%
% The recovered Phase 1 open-loop poles are:
%   -3.2548 +/- 1.7168i
%   -0.0052 +/- 0.1461i
%
% The recovered visible Phase 2 short-period closed-loop pair is:
%   -3.5534 +/- 2.0426i
%
% Exact A, B, Kq, U0, h0, and actuator limits were not recoverable from
% the retained source material. Do NOT fabricate them. Export the actual
% Phase 1/2 values with import_phase1_model.m.
%
% Usage:
%   cfg = phase3_config;
%
% or:
%   cfg = phase3_config('/path/to/phase3_autopilot_and_flight_control');

if nargin < 1 || isempty(project_root)
    this_file = mfilename('fullpath');
    matlab_dir = fileparts(this_file);
    project_root = fileparts(matlab_dir);
end

cfg.paths.project_root = project_root;
cfg.paths.matlab_dir   = fullfile(project_root, 'matlab');
cfg.paths.data_dir     = fullfile(project_root, 'data');
cfg.paths.figures_dir  = fullfile(project_root, 'figures');
cfg.paths.results_dir  = fullfile(project_root, 'results');
cfg.paths.model_mat    = fullfile(cfg.paths.data_dir, ...
                                  'phase1_longitudinal_model.mat');

% State convention used throughout the Phase 3 documentation.
cfg.state_names = {'u','w','q','theta'};
cfg.idx.u       = 1;
cfg.idx.w       = 2;
cfg.idx.q       = 3;
cfg.idx.theta   = 4;

% The Phase 3 pitch controller uses the elevator input.
cfg.input.elevator_index = 1;

%% Recovered baseline values from Phase 1/2 history
cfg.baseline.phase1_poles = [ ...
    -3.2548 + 1.7168i
    -3.2548 - 1.7168i
    -0.0052 + 0.1461i
    -0.0052 - 0.1461i ];

cfg.baseline.phase2_visible_short_period = [ ...
    -3.5534 + 2.0426i
    -3.5534 - 2.0426i ];

% Warning-only comparison tolerance. A different model version can legitimately
% have different poles.
cfg.validation.pole_match_tolerance = 5e-3;

%% Simulation settings
cfg.sim.dt              = 0.01;     % s
cfg.sim.pitch_t_final   = 60;       % s
cfg.sim.altitude_t_final = 300;     % s
cfg.sim.disturbance_t_final = 60;   % s

cfg.sim.x0 = zeros(4,1);

%% Pitch-command test
% This is a TEST COMMAND, not an aircraft parameter.
cfg.pitch.theta_cmd_deg = 5;

%% State-feedback pole-placement targets
% Enter either:
%   cfg.sf.desired_poles = [p1 p2 p3 p4];
%
% or specify modal targets below and leave desired_poles empty.
%
% Leaving all values empty/NaN causes the pole-placement design to be skipped.
cfg.sf.desired_poles = [];

cfg.sf.targets.wn_short_period = NaN;
cfg.sf.targets.zeta_short_period = NaN;
cfg.sf.targets.wn_phugoid = NaN;
cfg.sf.targets.zeta_phugoid = NaN;

%% LQR initial tuning
% These are INITIAL DESIGN NORMALIZATION VALUES, not sourced Cessna 182
% physical limits. Replace them with justified allowable excursions before
% publishing final portfolio results.
%
% x = [u, w, q, theta]^T
cfg.lqr.state_max = [ ...
    5.0;                % |u|     m/s
    3.0;                % |w|     m/s
    deg2rad(10);        % |q|     rad/s (10 deg/s)
    deg2rad(8) ];       % |theta| rad   (8 deg)

cfg.lqr.elevator_design_max = deg2rad(15); % rad; tuning normalization only

cfg.lqr.Q = diag(1 ./ (cfg.lqr.state_max.^2));
cfg.lqr.R = 1 / (cfg.lqr.elevator_design_max^2);

%% Altitude-hold outer-loop settings
% The four-state Phase 1 model does NOT contain altitude. Phase 3 augments
% altitude using:
%
%       h_dot ~= U0*theta - w
%
% for small perturbations about approximately level flight, with body-z
% positive down and altitude positive up.
%
% Enter gains only after U0 has been restored from the actual Phase 1 model.
cfg.altitude.command_m = 100;   % test command: altitude perturbation [m]
cfg.altitude.Kp = NaN;          % rad/m
cfg.altitude.Ki = NaN;          % rad/(m*s)

% Optional pitch-command limiter generated by the altitude controller.
% NaN means no limiter.
cfg.altitude.theta_command_limit_deg = NaN;

%% Actuator model
% Exact actuator data were not recovered. Keep disabled until sourced or
% explicitly adopted as a documented modeling assumption.
cfg.actuator.enable = false;
cfg.actuator.time_constant_s = NaN;
cfg.actuator.position_limit_deg = NaN;

%% Disturbance-rejection test
cfg.disturbance.x0 = zeros(4,1);
cfg.disturbance.x0(cfg.idx.theta) = deg2rad(2);  % test perturbation
cfg.disturbance.theta_recovery_tolerance_deg = 0.1;

%% Output behavior
cfg.output.save_figures = true;
cfg.output.save_results = true;
cfg.output.close_existing_figures = true;

end
